### ISSUE TITLE
Make Resolver Interface Extensible

### ISSUE THREAD

**Issue by yunong** [joyent/node-cueball#121]
I'd like to use cueball as a load balancer. I'd like to be able to extend the `Resolver` interface with my own custom implementation. From the looks of the code, it looks like I can just inherit the `CueBallResolver`,; however, https://github.com/joyent/node-cueball/blob/master/lib/resolver.js#L19 states that it's for "testing only". 

Could you provide some guidance on whether this interface is stable and is available for public consumption?

**Comment by arekinath** [comment]
Currently, the Resolver "interface" itself is considered stable (in that, you should expect that if you implement your own resolver-like object that obeys the interface as documented, including the state graph, then it will continue working unless we have a documented major-bump API break for it).

The CueBallResolver/ResolverFSM class itself though is not considered public API of the library. It's an adapter we set up to avoid having to rewrite some of the old DNS resolver code when we changed to the current Resolver interface in 1.0.0, and may eventually go away.

If you want an example of a Resolver interface implementation outside cueball, [this](https://gist.github.com/arekinath/878c26c956fba5aac13843d9a8d18dc9) is an example of one that gets its backends from manatee. It uses the same `mooremachine` library to provide the state machine bits there, but you don't even have to use that, as long as you provide the interface cueball expects (the `'stateChanged'` event, `isInState()` and `getState()`).

I hope this sounds reasonable -- if it is, we might want to make this bug into a documentation bug to improve the way it's explained and illustrated there (perhaps with an example 3rd party resolver interface implementation as an exhibit)

**Comment by yunong** [comment]
@arekinath Thanks for the detailed reply! Does documentation exist somewhere to plug in a custom resolver to the Agent function? I see this code here: https://github.com/joyent/node-cueball/blob/master/lib/agent.js#L34 which looks like the base agent takes a list of resolvers. Is this the right place to plug in a custom resolver?

**Comment by arekinath** [comment]
Ah, sadly, the Agent today doesn't have API for manually overriding the resolver instance in use. This is because it auto-generates the pools based on the hostname you give it in the URI you ask the agent to connect to (it uses the `resolverForIpOrDomain` function, so this could be a DNSResolver or a StaticIPResolver). I have #122 open at the moment to add new API to the Agent to let you override the resolver instance to be used for a particular hostname (though you'll likely have to do it before you make any HTTP requests through it).

I also plan to add some API to Agent at some point to let you find out more about the pools + resolvers it creates and what state they're in (since currently there isn't a documented way to tell e.g. if the pool behind an Agent has failed or not, except by making a request and having it fail, which is not very nice). It's a bit of a weak spot in the current API.

**Comment by yunong** [comment]
Thanks for the clarification. Any idea on a rough timeline on when #122 might get added?

**Comment by yunong** [comment]
Thanks for the clarification. Any idea on a rough timeline on when #122 might get added?

**Comment by arekinath** [comment]
#122 is released in 2.3.0 now. There is a mistake in the documentation, though, I'm afraid, and I'd like to add another couple of options that might be useful (see #125 and #126). If you're not using client TLS certificates, and don't need to connect to self-signed TLS servers, these probably won't bother you, and 2.3.0 should be perfectly useable.

Let me know if you have any problems!

**Comment by yunong** [comment]
Hooray! Thanks for this. I'll take a look at using this this week.

**Comment by hekike** [comment]
@arekinath thanks, here is a `StaticIPResolver` with add/remove interface: https://github.com/hekike/cueball-resolver ;)
